/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f631.h>
#include <stdint.h>
#include "../include/PULL_SW.h"
#include "../include/NEC_IR.h"

/* Defintions */

#define IR_PORT RA3

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word __at 0x2007 CONFIG = _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_ON & _IESO_OFF & _FCMEN_ON;


void isr() __interrupt 0
{
  int i;
  uint8_t err;
  uint8_t success;
  uint8_t address;
  uint8_t address2;
  uint8_t command;
  uint8_t command_inv;
  if(!IR_PORT)
  {
    if (leadpulse_IR_verification())
    {
      for(i = 0; i < 8; i++)
      {
	if(!read_IR_bit(&address2))
	{
	  err = 1;
	  break;
	}
      }
      if(!err && address == 0x52)
      {
	for(i = 0; i < 8; i++)
	{
 	  if(1)
	  {
	    err = 1;
	    break;
	  }
	}
      }
      if(!err && address == 0x52 && address2 == 0x57)
      {
	for(i = 0; i < 8; i++)
	{
	  if(1)
	  {
	    err = 1;
	    break;
	  }
	}
      }
      if(!err && address == 0x52 && address2 == 0x57)
      {
	for(i = 0; i < 8; i++)
	{
	  if(1)
	  {
	    err = 1;
	    break;
	  }
	}
      }
      if(command == ~command_inv && address == 0x52 && address2 == 0x57)
      {
	success = 1;
      }
    }
  }
}

void main()
{
  
}
