// Scart Switch PIC program NON IR VERSION
/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f630.h>

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word __at 0x2007 CONFIG = _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _BODEN & _CP_OFF & _CPD_OFF;

/* ----------------------------------------------------------------------- */
/* Functions */
#include "functions.h"
int placeholder;

/* ----------------------------------------------------------------------- */


void main() {
  unsigned int curr_scart = 0; // Active scart port [0-7]
  OPTION_REG = 0b01111111; // PORTA pull ups are enabled, setting up TMR0
  PORTC = 0xFE; // PORTC is going to be HIGH when set to OUTPUT, except PORTC0, which is LOW
  // TODO Save last scart position to flash, so that it can be loaded on next bootup... but with 100 000 write cycles... is it justified?
  PORTA = 0x03; // First 2 PORTA init. to HIGH
  TRISC = 0x00; // Setting PORTC to output
  TRISA = 0xFC; // 2 PORTA pins to OUTPUT, rest stays on INPUT
  // main loop
  while(1)
  {
    if(RA4 == 1 && RA5 == 0) // If A4 is HIGH and A5 is LOW, then move active scart input to the previous one (move backwards)
    {
      switch_backwards(&curr_scart);
      delay_ms(200); // Wait ~0.5s before next check
    }
    if(RA5 == 1 && RA4 == 0) // If A5 is HIGH and A4 is LOW, then move active scart input to the next one (move forward)
    {
      switch_forward(&curr_scart);
      delay_ms(200); // Wait ~0.5s before next check
    }
    // TODO Maybe implement switching through selecting first the number then switching to it... from anywhere
  }
}

